### ISSUE TITLE
Please add a way to open links in a browser

### ISSUE THREAD

**Issue by andreicristianpetcu** [gsurrel/FacebookNotifications#18] opened 2016-05-31 09:49 UTC
I sometimes get links on Facebook and I want to be able to bookmark them or send them to other people.

Can you please add a "Open in web broser" button?

Thank you

**Comment by gsurrel** [comment] 2016-05-31 09:53
I will add two buttons to the toolbar: "Open in browser" and "Share". I guess it will do the trick for you :)

**Comment by andreicristianpetcu** [comment] 2016-05-31 10:27
Yes. Thank you!

**Comment by hirvinen** [comment] 2016-09-18 11:16
An optionally visible share button is added in #23, it can also be used to send to browser but I'm thinking of maybe doing a separate browser button as well.

**Comment by gsurrel** [comment] 2016-09-21 14:18
I think so, I'll close it for now, reopen it if you don't see the expected behavior. Thanks @hirvinen for the patch.
I'm not so sure the dedicated "Open in browser" is needed because it's indeed available in the share menu.

**Closed as completed by gsurrel** 2016-09-21 14:18 UTC
Labels: enhancement

**Comment by andreicristianpetcu** [comment] 2016-09-22 18:43
Yay! This is awesome! I updated from F-Droid and the share button works great! I use it in tandem with [Flashify](https://f-droid.org/repository/browse/?fdfilter=flash&fdid=com.nightshadelabs.anotherbrowser)
